//------------------------------------------------------------------------------
// <auto-generated>
//     ??肄붾뱶???꾧뎄瑜??ъ슜?섏뿬 ?앹꽦?섏뿀?듬땲??
//     ?고???踰꾩쟾:4.0.30319.42000
//
//     ?뚯씪 ?댁슜??蹂寃쏀븯硫??섎せ???숈옉??諛쒖깮?????덉쑝硫? 肄붾뱶瑜??ㅼ떆 ?앹꽦?섎㈃
//     ?대윭??蹂寃??댁슜???먯떎?⑸땲??
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.ModernUI.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   吏??솕??臾몄옄???깆쓣 李얘린 ?꾪븳 媛뺣젰???뺤떇??由ъ냼???대옒?ㅼ엯?덈떎.
    /// </summary>
    // ???대옒?ㅻ뒗 ResGen ?먮뒗 Visual Studio? 媛숈? ?꾧뎄瑜??듯빐 StronglyTypedResourceBuilder
    // ?대옒?ㅼ뿉???먮룞?쇰줈 ?앹꽦?섏뿀?듬땲??
    // 硫ㅻ쾭瑜?異붽??섍굅???쒓굅?섎젮硫?.ResX ?뚯씪???몄쭛???ㅼ쓬 /str ?듭뀡???ъ슜?섏뿬 ResGen??
    // ?ㅼ떆 ?ㅽ뻾?섍굅??VS ?꾨줈?앺듃瑜??ㅼ떆 鍮뚮뱶?섏떗?쒖삤.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   ???대옒?ㅼ뿉???ъ슜?섎뒗 罹먯떆??ResourceManager ?몄뒪?댁뒪瑜?諛섑솚?⑸땲??
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.ModernUI.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??媛뺣젰???뺤떇??由ъ냼???대옒?ㅻ? ?ъ슜?섏뿬 紐⑤뱺 由ъ냼??議고쉶??????꾩옱 ?ㅻ젅?쒖쓽 CurrentUICulture ?띿꽦??
        ///   ?ъ젙?섑빀?덈떎.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Cancel怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cre_ate怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Move {
            get {
                return ResourceManager.GetString("Button_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _No怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Retry怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Select怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Yes怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Guid怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Command_NewGuid {
            get {
                return ResourceManager.GetString("Command_NewGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Command_NextSearchedItem {
            get {
                return ResourceManager.GetString("Command_NextSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Command_PrevSearchedItem {
            get {
                return ResourceManager.GetString("Command_PrevSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Command_Show {
            get {
                return ResourceManager.GetString("Command_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type word to search.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Comment_Filter {
            get {
                return ResourceManager.GetString("Comment_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type &apos;{0}&apos;怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Comment_TypeText {
            get {
                return ResourceManager.GetString("Comment_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case sensitive怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CategoryName {
            get {
                return ResourceManager.GetString("Label_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Path怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CategoryPath {
            get {
                return ResourceManager.GetString("Label_CategoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Name怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CurrentName {
            get {
                return ResourceManager.GetString("Label_CurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Path怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CurrentPath {
            get {
                return ResourceManager.GetString("Label_CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Folder怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_CurrentTargetPath {
            get {
                return ResourceManager.GetString("Label_CurrentTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Name怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_NewName {
            get {
                return ResourceManager.GetString("Label_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folder怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_TargetPath {
            get {
                return ResourceManager.GetString("Label_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use glob pattern怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Label_UseGlobPattern {
            get {
                return ResourceManager.GetString("Label_UseGlobPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to create it?怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_ConfirmToCreate {
            get {
                return ResourceManager.GetString("Message_ConfirmToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it?怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_ConfirmToDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save it?怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_ConfirmToSave {
            get {
                return ResourceManager.GetString("Message_ConfirmToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Folder.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_CreatingCategory {
            get {
                return ResourceManager.GetString("Message_CreatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_Deleting {
            get {
                return ResourceManager.GetString("Message_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_Moving {
            get {
                return ResourceManager.GetString("Message_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renaming.怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Message_Renaming {
            get {
                return ResourceManager.GetString("Message_Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Now怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Text_DeleteNow {
            get {
                return ResourceManager.GetString("Text_DeleteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Filter怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_EditFilter {
            get {
                return ResourceManager.GetString("Title_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_Move {
            get {
                return ResourceManager.GetString("Title_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_NewCategory {
            get {
                return ResourceManager.GetString("Title_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_Rename {
            get {
                return ResourceManager.GetString("Title_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Color怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string Title_SelectColor {
            get {
                return ResourceManager.GetString("Title_SelectColor", resourceCulture);
            }
        }
    }
}
