//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???„êµ¬ë¥??¬ìš©?˜ì—¬ ?ì„±?˜ì—ˆ?µë‹ˆ??
//     ?°í???ë²„ì „:4.0.30319.42000
//
//     ?Œì¼ ?´ìš©??ë³€ê²½í•˜ë©??˜ëª»???™ì‘??ë°œìƒ?????ˆìœ¼ë©? ì½”ë“œë¥??¤ì‹œ ?ì„±?˜ë©´
//     ?´ëŸ¬??ë³€ê²??´ìš©???ì‹¤?©ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.ModernUI.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   ì§€??™”??ë¬¸ì???±ì„ ì°¾ê¸° ?„í•œ ê°•ë ¥???•ì‹??ë¦¬ì†Œ???´ë˜?¤ì…?ˆë‹¤.
    /// </summary>
    // ???´ë˜?¤ëŠ” ResGen ?ëŠ” Visual Studio?€ ê°™ì? ?„êµ¬ë¥??µí•´ StronglyTypedResourceBuilder
    // ?´ë˜?¤ì—???ë™?¼ë¡œ ?ì„±?˜ì—ˆ?µë‹ˆ??
    // ë©¤ë²„ë¥?ì¶”ê??˜ê±°???œê±°?˜ë ¤ë©?.ResX ?Œì¼???¸ì§‘???¤ìŒ /str ?µì…˜???¬ìš©?˜ì—¬ ResGen??
    // ?¤ì‹œ ?¤í–‰?˜ê±°??VS ?„ë¡œ?íŠ¸ë¥??¤ì‹œ ë¹Œë“œ?˜ì‹­?œì˜¤.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   ???´ë˜?¤ì—???¬ìš©?˜ëŠ” ìºì‹œ??ResourceManager ?¸ìŠ¤?´ìŠ¤ë¥?ë°˜í™˜?©ë‹ˆ??
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.ModernUI.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??ê°•ë ¥???•ì‹??ë¦¬ì†Œ???´ë˜?¤ë? ?¬ìš©?˜ì—¬ ëª¨ë“  ë¦¬ì†Œ??ì¡°íšŒ???€???„ì¬ ?¤ë ˆ?œì˜ CurrentUICulture ?ì„±??
        ///   ?¬ì •?˜í•©?ˆë‹¤.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Cancelê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Closeê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cre_ateê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Deleteê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Moveê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Move {
            get {
                return ResourceManager.GetString("Button_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Noê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OKê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Renameê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Retryê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Selectê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Yesê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hideê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Guidê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Command_NewGuid {
            get {
                return ResourceManager.GetString("Command_NewGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nextê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Command_NextSearchedItem {
            get {
                return ResourceManager.GetString("Command_NextSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prevê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Command_PrevSearchedItem {
            get {
                return ResourceManager.GetString("Command_PrevSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Showê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Command_Show {
            get {
                return ResourceManager.GetString("Command_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type word to search.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Comment_Filter {
            get {
                return ResourceManager.GetString("Comment_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type &apos;{0}&apos;ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Comment_TypeText {
            get {
                return ResourceManager.GetString("Comment_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case sensitiveê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Nameê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CategoryName {
            get {
                return ResourceManager.GetString("Label_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Pathê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CategoryPath {
            get {
                return ResourceManager.GetString("Label_CategoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commentê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Nameê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CurrentName {
            get {
                return ResourceManager.GetString("Label_CurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Pathê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CurrentPath {
            get {
                return ResourceManager.GetString("Label_CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Folderê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_CurrentTargetPath {
            get {
                return ResourceManager.GetString("Label_CurrentTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Nameê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_NewName {
            get {
                return ResourceManager.GetString("Label_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folderê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_TargetPath {
            get {
                return ResourceManager.GetString("Label_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use glob patternê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Label_UseGlobPattern {
            get {
                return ResourceManager.GetString("Label_UseGlobPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to create it?ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_ConfirmToCreate {
            get {
                return ResourceManager.GetString("Message_ConfirmToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it?ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_ConfirmToDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save it?ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_ConfirmToSave {
            get {
                return ResourceManager.GetString("Message_ConfirmToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Folder.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_CreatingCategory {
            get {
                return ResourceManager.GetString("Message_CreatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_Deleting {
            get {
                return ResourceManager.GetString("Message_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_Moving {
            get {
                return ResourceManager.GetString("Message_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renaming.ê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Message_Renaming {
            get {
                return ResourceManager.GetString("Message_Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Nowê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Text_DeleteNow {
            get {
                return ResourceManager.GetString("Text_DeleteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleteê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Filterê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_EditFilter {
            get {
                return ResourceManager.GetString("Title_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_Move {
            get {
                return ResourceManager.GetString("Title_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folderê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_NewCategory {
            get {
                return ResourceManager.GetString("Title_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renameê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_Rename {
            get {
                return ResourceManager.GetString("Title_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Colorê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string Title_SelectColor {
            get {
                return ResourceManager.GetString("Title_SelectColor", resourceCulture);
            }
        }
    }
}
