//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.ModernUI.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.ModernUI.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cre_ate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Move {
            get {
                return ResourceManager.GetString("Button_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Retry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_Hide {
            get {
                return ResourceManager.GetString("Command_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_NextSearchedItem {
            get {
                return ResourceManager.GetString("Command_NextSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_PrevSearchedItem {
            get {
                return ResourceManager.GetString("Command_PrevSearchedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_Show {
            get {
                return ResourceManager.GetString("Command_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type word to search.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_Filter {
            get {
                return ResourceManager.GetString("Comment_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_TypeText {
            get {
                return ResourceManager.GetString("Comment_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case sensitive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CategoryName {
            get {
                return ResourceManager.GetString("Label_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CategoryPath {
            get {
                return ResourceManager.GetString("Label_CategoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentName {
            get {
                return ResourceManager.GetString("Label_CurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentPath {
            get {
                return ResourceManager.GetString("Label_CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentTargetPath {
            get {
                return ResourceManager.GetString("Label_CurrentTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NewName {
            get {
                return ResourceManager.GetString("Label_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TargetPath {
            get {
                return ResourceManager.GetString("Label_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use glob pattern과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UseGlobPattern {
            get {
                return ResourceManager.GetString("Label_UseGlobPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to create it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToCreate {
            get {
                return ResourceManager.GetString("Message_ConfirmToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToSave {
            get {
                return ResourceManager.GetString("Message_ConfirmToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CreatingCategory {
            get {
                return ResourceManager.GetString("Message_CreatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Deleting {
            get {
                return ResourceManager.GetString("Message_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Moving {
            get {
                return ResourceManager.GetString("Message_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renaming.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Renaming {
            get {
                return ResourceManager.GetString("Message_Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_DeleteNow {
            get {
                return ResourceManager.GetString("Text_DeleteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditFilter {
            get {
                return ResourceManager.GetString("Title_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Move {
            get {
                return ResourceManager.GetString("Title_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewCategory {
            get {
                return ResourceManager.GetString("Title_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Rename {
            get {
                return ResourceManager.GetString("Title_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SelectColor {
            get {
                return ResourceManager.GetString("Title_SelectColor", resourceCulture);
            }
        }
    }
}
