//------------------------------------------------------------------------------
// <auto-generated>
//     ??肄붾뱶???꾧뎄瑜??ъ슜?섏뿬 ?앹꽦?섏뿀?듬땲??
//     ?고???踰꾩쟾:4.0.30319.42000
//
//     ?뚯씪 ?댁슜??蹂寃쏀븯硫??섎せ???숈옉??諛쒖깮?????덉쑝硫? 肄붾뱶瑜??ㅼ떆 ?앹꽦?섎㈃
//     ?대윭??蹂寃??댁슜???먯떎?⑸땲??
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.ModernUI.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   吏??솕??臾몄옄???깆쓣 李얘린 ?꾪븳 媛뺣젰???뺤떇??由ъ냼???대옒?ㅼ엯?덈떎.
    /// </summary>
    // ???대옒?ㅻ뒗 ResGen ?먮뒗 Visual Studio? 媛숈? ?꾧뎄瑜??듯빐 StronglyTypedResourceBuilder
    // ?대옒?ㅼ뿉???먮룞?쇰줈 ?앹꽦?섏뿀?듬땲??
    // 硫ㅻ쾭瑜?異붽??섍굅???쒓굅?섎젮硫?.ResX ?뚯씪???몄쭛???ㅼ쓬 /str ?듭뀡???ъ슜?섏뿬 ResGen??
    // ?ㅼ떆 ?ㅽ뻾?섍굅??VS ?꾨줈?앺듃瑜??ㅼ떆 鍮뚮뱶?섏떗?쒖삤.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   ???대옒?ㅼ뿉???ъ슜?섎뒗 罹먯떆??ResourceManager ?몄뒪?댁뒪瑜?諛섑솚?⑸땲??
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.ModernUI.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??媛뺣젰???뺤떇??由ъ냼???대옒?ㅻ? ?ъ슜?섏뿬 紐⑤뱺 由ъ냼??議고쉶??????꾩옱 ?ㅻ젅?쒖쓽 CurrentUICulture ?띿꽦??
        ///   ?ъ젙?섑빀?덈떎.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _File怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quit怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tool怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string MenuItem_Tool {
            get {
                return ResourceManager.GetString("MenuItem_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View怨??) ?좎궗??吏??솕??臾몄옄?댁쓣 李얠뒿?덈떎.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
    }
}
