//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???„êµ¬ë¥??¬ìš©?˜ì—¬ ?ì„±?˜ì—ˆ?µë‹ˆ??
//     ?°í???ë²„ì „:4.0.30319.42000
//
//     ?Œì¼ ?´ìš©??ë³€ê²½í•˜ë©??˜ëª»???™ì‘??ë°œìƒ?????ˆìœ¼ë©? ì½”ë“œë¥??¤ì‹œ ?ì„±?˜ë©´
//     ?´ëŸ¬??ë³€ê²??´ìš©???ì‹¤?©ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.ModernUI.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   ì§€??™”??ë¬¸ì???±ì„ ì°¾ê¸° ?„í•œ ê°•ë ¥???•ì‹??ë¦¬ì†Œ???´ë˜?¤ì…?ˆë‹¤.
    /// </summary>
    // ???´ë˜?¤ëŠ” ResGen ?ëŠ” Visual Studio?€ ê°™ì? ?„êµ¬ë¥??µí•´ StronglyTypedResourceBuilder
    // ?´ë˜?¤ì—???ë™?¼ë¡œ ?ì„±?˜ì—ˆ?µë‹ˆ??
    // ë©¤ë²„ë¥?ì¶”ê??˜ê±°???œê±°?˜ë ¤ë©?.ResX ?Œì¼???¸ì§‘???¤ìŒ /str ?µì…˜???¬ìš©?˜ì—¬ ResGen??
    // ?¤ì‹œ ?¤í–‰?˜ê±°??VS ?„ë¡œ?íŠ¸ë¥??¤ì‹œ ë¹Œë“œ?˜ì‹­?œì˜¤.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   ???´ë˜?¤ì—???¬ìš©?˜ëŠ” ìºì‹œ??ResourceManager ?¸ìŠ¤?´ìŠ¤ë¥?ë°˜í™˜?©ë‹ˆ??
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.ModernUI.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??ê°•ë ¥???•ì‹??ë¦¬ì†Œ???´ë˜?¤ë? ?¬ìš©?˜ì—¬ ëª¨ë“  ë¦¬ì†Œ??ì¡°íšŒ???€???„ì¬ ?¤ë ˆ?œì˜ CurrentUICulture ?ì„±??
        ///   ?¬ì •?˜í•©?ˆë‹¤.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Fileê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Helpê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quitê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Toolê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string MenuItem_Tool {
            get {
                return ResourceManager.GetString("MenuItem_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Viewê³??€) ? ì‚¬??ì§€??™”??ë¬¸ì?´ì„ ì°¾ìŠµ?ˆë‹¤.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
    }
}
